---
ID: "08715e0e-334f-42be-967b-07fadc537372"
Parent: "9d8cb562-d9d8-4642-b347-550a884af1c4"
Template: "9d8cb562-d9d8-4642-b347-550a884af1c4"
Path: /sitecore/templates/Feature/RichTextWithStats/Rendering Parameters/Rich Text with Statistic Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230420T023416Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "477495ca-5580-4c63-97b5-5571765ec482"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230420T023446Z
