---
ID: "4d0b572b-2d43-49ce-b0f1-9e313450f992"
Parent: "9acffd78-ef6b-4021-b24d-16c06b22909c"
Template: "9acffd78-ef6b-4021-b24d-16c06b22909c"
Path: /sitecore/templates/Project/ISC2/Folder Types/Page Component Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{5CEE9538-EAA7-47A7-956B-87CD2DDE3374}"
- ID: "a791f095-2521-4b4d-bef9-21dda221f608"
  Hint: __Style
  Value: "font-size: 90%; font-style: italic;"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230420T025917Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rshah
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rshah
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "21f77211-cae2-49d6-a6d0-e3044088a173"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230509T130859Z
