---
ID: "4998c8f2-6903-4810-8c71-4f41a17733c6"
Parent: "4d420ab9-bec8-4edd-9a86-d9aba7506e1a"
Template: "4d420ab9-bec8-4edd-9a86-d9aba7506e1a"
Path: /sitecore/templates/Feature/Shared Components/Related Insight/Dynamic Related Insights Folder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: apps/32x32/forms &#40;1&#41;.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{EC9FD0F7-0094-4E79-8AC7-ED6CB2884893}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230529T102206Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "441d738e-5b5e-4ce8-84df-8639927020fd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230913T081856Z
