---
ID: "fd38f054-0e50-418b-aeb8-74fa19f8d660"
Parent: "0fa660f9-ab1e-48ed-ad18-6567ad535b66"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/Feature/Product Tabs/Product Tabs
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230509T121810Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d683301b-e6dd-4e66-ba16-46e77b0f8b88"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230509T121810Z
