---
ID: "483a74fe-6ed1-4b2a-a2e4-06ffcbc3fc2a"
Parent: "d39e25bf-0c69-4ef8-bc8d-12bc7baadd6e"
Template: "d39e25bf-0c69-4ef8-bc8d-12bc7baadd6e"
Path: /sitecore/templates/Foundation/Base/List Types/Topic/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "236b1d0f-e8fd-4653-9c2c-07caa0955e63"
      Hint: name
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230428T175212Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f4e4347f-6d74-4463-86af-22673ef8f9e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230428T183013Z
