---
ID: "731b02b0-10ef-4cbb-b613-a50d550e4c87"
Parent: "4716bfe8-f5b9-468b-a78d-46b9cae2f94d"
Template: "4716bfe8-f5b9-468b-a78d-46b9cae2f94d"
Path: /sitecore/templates/Feature/Tabs/Rebrand Horizontal Tabs/Horizontal Tab Container/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/log_in.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{7A9A60D0-BA4D-4E07-9B5D-4B4AC50F5874}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230516T082603Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "90f6ed72-0695-49c0-a267-39b4c5fc6e76"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230801T081200Z
