---
ID: "74bcfa7b-066e-4087-b9ca-e404e0df1010"
Parent: "ff1d5bb9-e942-4157-bb47-bbac9aea166c"
Template: "ff1d5bb9-e942-4157-bb47-bbac9aea166c"
Path: /sitecore/templates/Feature/Accordion/Link Accordion Section/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{6CF840FA-5345-4CA6-BB6C-FD349F28923D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230428T201236Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5893823d-964b-4218-9182-840b58301f68"
    - ID: "8ef41b5f-ed08-4aaf-bb42-6ca51f7d7ab9"
      Hint: title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230429T202609Z
