---
ID: "84a26a9c-1539-45f2-b120-72a1efd1009f"
Parent: "33b7dcbd-709a-40b3-9597-9e59d95d2c0b"
Template: "33b7dcbd-709a-40b3-9597-9e59d95d2c0b"
Path: /sitecore/templates/Foundation/Base/_workFlowAccess/__Standard Values
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{68F795DE-E368-471F-92D8-07F08E74423F}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{68F795DE-E368-471F-92D8-07F08E74423F}"
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\ISC2 Web Admin|pd|+item:delete|+item:admin|+item:write|+item:read|^*|+item:rename|+item:create|pe|+item:delete|+item:admin|+item:write|+item:read|^*|+item:rename|+item:create|ar|sitecore\ISC2 Author|pd|+item:delete|+item:admin|+item:write|+item:read|^*|+item:create|pe|+item:delete|+item:admin|+item:write|+item:read|^*|+item:create|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240401T130901Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{1247BD4C-661E-4F34-9073-D72512D8495E}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pdubey
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pdubey
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eff7f7a6-02b6-49ba-b77a-f99613badc2a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240702T170058Z
