---
ID: "9cc86aad-8623-44d6-8667-8cf5e97e9d35"
Parent: "6a0f89d3-1333-4126-9a8f-ade97b5b462e"
Template: "d2a6884c-04d5-4089-a64e-d27ca9d68d4c"
Path: /sitecore/content/ISC2/Main/Presentation/Placeholder Settings/Partial Design/Product Landing Page
SharedFields:
- ID: "7256bdab-1fd2-49dd-b205-cb4873d2917c"
  Hint: Placeholder Key
  Value: "sxa-product-landing-page"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240614T133522Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a3f1f14a-42b4-485f-898b-3b89a09d725e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240618T140813Z
