---
ID: "e168f829-4f55-4e94-a2a2-17a756a6d6f1"
Parent: "90df53f0-c7e6-47c0-9b60-e4c05faa654b"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: /sitecore/layout/Renderings/Feature/Tabs/ProductTabs/Product Tabs Container
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: ProductTabsContainer
- ID: "069a8361-b1cd-437c-8c32-a3be78941446"
  Hint: Placeholders
  Value: "{952764A0-66DF-430B-8C84-3273D8B0494C}"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Feature/Tabs/Product Tabs/Product Tabs
- ID: "3d08db46-2267-41b0-bc52-be69fd618633"
  Hint: Cacheable
  Value: 1
- ID: "8b6d532b-6128-4486-a044-ca06d90948ba"
  Hint: VaryByData
  Value: 1
- ID: "b0b15510-b138-470e-8f33-8da2e228aafe"
  Hint: Rendering Contents Resolver
  Value: "{3DF775BF-3F56-446F-9D81-43DE64DA4DDA}"
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "./Page Components|query:$site/*[@@name='Data']/*[@@templatename='Product Tabs Folder']|query:$sharedSites/*[@@name='Data']/*[@@templatename='Product Tabs Folder ']"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230509T133240Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a6dfd6b4-1dcf-4ed7-85c9-9a97c7007602"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230522T085055Z
