---
ID: "b1931f6b-1d38-4cb0-9aaf-c1594f1b567b"
Parent: "4e6f23cb-0dff-4e45-9bb7-77efd666bbc2"
Template: "4e6f23cb-0dff-4e45-9bb7-77efd666bbc2"
Path: /sitecore/templates/Feature/Tabs/Horizontal Tabs/Horizontal Tab Container/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/log_in.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{79501051-C722-40AB-97BD-D48DA99AF4D5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230516T082603Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "98a72fa5-2bd3-46c1-b4ad-e130c2e8d681"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pyewale
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230517T110035Z
