---
ID: "8743d5c4-6364-4cc3-abd9-b63c53ccab4e"
Parent: "c5ffdf5c-fe78-449c-a6ab-f995bccf45c4"
Template: "c5ffdf5c-fe78-449c-a6ab-f995bccf45c4"
Path: /sitecore/templates/Feature/Shared Components/Slider/Slider Container/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{900E551B-F17D-4550-BC4C-003C514A7E04}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230606T104317Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e80e76e7-2696-4a49-a2f5-cd91fbbf9344"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230606T104352Z
