---
ID: "04ada0c3-20a1-4244-b90e-885a3d8cfda8"
Parent: "d10934c2-0630-4b53-8934-b45d19198e16"
Template: "eca6e291-bb55-47ab-bd02-be76b1bc884f"
Path: /sitecore/system/Settings/Html Editor Profiles/Rich Text Minimum/Configuration Type
SharedFields:
- ID: "ff617570-33a4-4d0e-931e-ffeb9fab450f"
  Hint: Type
  Value: Sitecore.Shell.Controls.RichTextEditor.EditorConfiguration,Sitecore.Client
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090811T153354
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4852930-0d2f-4e27-8fb6-3a4e85005aad"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240604T161655Z
