// Requested and provided by Rajkumar
export const POSTAL_CODES_PATTERNS = {
  AF: /^\d{4}$/, // Afghanistan (Example: 1001)
  AL: /^\d{4}$/, // Albania (Example: 1001)
  DZ: /^\d{5}$/, // Algeria (Example: 16027)
  AD: /^AD\d{3}$/, // Andorra (Example: AD500)
  AO: null, // Angola (No postal code system)
  AG: null, // Antigua and Barbuda (No postal code system)
  AR: /^[A-Za-z]\d{4}$/, // Argentina (Example: C1001)
  AM: /^\d{4}$/, // Armenia (Example: 0010)
  AU: /^\d{4}$/, // Australia (Example: 2000)
  AT: /^\d{4}$/, // Austria (Example: 1010)
  AZ: /^AZ\d{4}$/, // Azerbaijan (Example: AZ1000)
  BS: null, // Bahamas (No postal code system)
  BH: /^\d{3,4}$/, // Bahrain (Example: 317 or 4222)
  BD: /^\d{4}$/, // Bangladesh (Example: 1207)
  BB: /^BB\d{5}$/, // Barbados (Example: BB11000)
  BY: /^\d{6}$/, // Belarus (Example: 220030)
  BE: /^\d{4}$/, // Belgium (Example: 1000)
  BZ: null, // Belize (No postal code system)
  BJ: null, // Benin (No postal code system)
  BT: /^\d{5}$/, // Bhutan (Example: 11001)
  BO: null, // Bolivia (No postal code system)
  BA: /^\d{5}$/, // Bosnia and Herzegovina (Example: 71000)
  BW: null, // Botswana (No postal code system)
  BR: /^\d{5}-\d{3}$/, // Brazil (Example: 01000-000)
  BN: /^\d{4}$/, // Brunei (Example: BB3713)
  BG: /^\d{4}$/, // Bulgaria (Example: 1000)
  BF: null, // Burkina Faso (No postal code system)
  BI: null, // Burundi (No postal code system)
  KH: /^\d{5}$/, // Cambodia (Example: 12000)
  CM: null, // Cameroon (No postal code system)
  CA: /^[A-Za-z]\d[A-Za-z] ?\d[A-Za-z]\d$/, // Canada (Example: K1A 0B1)
  CV: null, // Cape Verde (No postal code system)
  CF: null, // Central African Republic (No postal code system)
  TD: null, // Chad (No postal code system)
  CL: /^\d{7}$/, // Chile (Example: 8320000)
  CN: /^\d{6}$/, // China (Example: 100000)
  CO: /^\d{6}$/, // Colombia (Example: 111221)
  KM: null, // Comoros (No postal code system)
  CR: /^\d{5}$/, // Costa Rica (Example: 10101)
  HR: /^\d{5}$/, // Croatia (Example: 10000)
  CU: /^\d{5}$/, // Cuba (Example: 10400)
  CY: /^\d{4}$/, // Cyprus (Example: 2000)
  CZ: /^\d{3} ?\d{2}$/, // Czech Republic (Example: 110 00)
  DK: /^\d{4}$/, // Denmark (Example: 1000)
  DJ: null, // Djibouti (No postal code system)
  DM: null, // Dominica (No postal code system)
  DO: /^\d{5}$/, // Dominican Republic (Example: 10101)
  EC: /^\d{6}$/, // Ecuador (Example: 170150)
  EG: /^\d{5}$/, // Egypt (Example: 11599)
  SV: /^\d{4}$/, // El Salvador (Example: 1101)
  GQ: null, // Equatorial Guinea (No postal code system)
  ER: null, // Eritrea (No postal code system)
  EE: /^\d{5}$/, // Estonia (Example: 10101)
  ET: /^\d{4}$/, // Ethiopia (Example: 1000)
  FJ: null, // Fiji (No postal code system)
  FI: /^\d{5}$/, // Finland (Example: 00100)
  FR: /^\d{5}$/, // France (Example: 75008)
  GA: null, // Gabon (No postal code system)
  GM: null, // Gambia (No postal code system)
  GE: /^\d{4}$/, // Georgia (Example: 0101)
  DE: /^\d{5}$/, // Germany (Example: 10115)
  GH: null, // Ghana (No postal code system)
  GR: /^\d{5}$/, // Greece (Example: 10563)
  GT: /^\d{5}$/, // Guatemala (Example: 01001)
  HT: /^\d{4}$/, // Haiti (Example: 6110)
  HU: /^\d{4}$/, // Hungary (Example: 1011)
  IS: /^\d{3}$/, // Iceland (Example: 101)
  IN: /^\d{6}$/, // India (Example: 110001)
  ID: /^\d{5}$/, // Indonesia (Example: 40115)
  IR: /^\d{5}-?\d{5}$/, // Iran (Example: 11369-57411)
  IQ: /^\d{5}$/, // Iraq (Example: 10001)
  IE: /^[A-Z0-9]{3} ?[A-Z0-9]{4}$/, // Ireland (Example: D02X285)
  IL: /^\d{5,7}$/, // Israel (Example: 91999)
  IT: /^\d{5}$/, // Italy (Example: 00100)
  JP: /^\d{3}-\d{4}$/, // Japan (Example: 100-0001)
  US: /^[0-9]{5}(-[0-9]{4})?$/, // United States (Example: 12345 or 12345-6789)
  VN: /^\d{6}$/, // Vietnam (Example: 700000)
};
